self_practices/practice_1/most_basic_app/accounts/urls.py
from django.urls import path

from .views import SignUpView

urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
]

self_practices/practice_1/most_basic_app/most_basic_app/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("", include(('rooms.urls', 'rooms'), namespace='rooms')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('tests/', include('tests.urls')),
]

self_practices/practice_1/most_basic_app/rooms/urls.py
from django.urls import path

from .views import SalonView, MutfakView, YatakOdaView, KucukOdaView, TuvaletView, ListRoomsView

urlpatterns = [
    path('', ListRoomsView.as_view(), name='koridor'),
    path('salon', SalonView.as_view(), name='salon'),
    path('mutfak', MutfakView.as_view(), name='mutfak'),
    path('yatakoda', YatakOdaView.as_view(), name='yatakoda'),
    path('kucukoda', KucukOdaView.as_view(), name='kucukoda'),
    path('tuvalet', TuvaletView.as_view(), name='tuvalet'),
    ]

self_practices/practice_1/most_basic_app/accounts/models.py
from django.db import models

# Create your models here.

self_practices/practice_1/most_basic_app/rooms/models.py
from django.db import models

# Create your models here.

class Salon(models.Model):
    name = models.CharField(max_length=200)
    type = models.CharField(max_length=200)

class Mutfak(models.Model):
    name = models.CharField(max_length=200)
    type = models.CharField(max_length=200)

class KucukOda(models.Model):
    name = models.CharField(max_length=200)
    type = models.CharField(max_length=200)

class YatakOda(models.Model):
    name = models.CharField(max_length=200)
    type = models.CharField(max_length=200)

class Tuvalet(models.Model):
    name = models.CharField(max_length=200)
    type = models.CharField(max_length=200)

self_practices/practice_1/most_basic_app/accounts/views.py
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render

# Create your views here.
from django.urls import reverse_lazy
from django.views.generic import CreateView


class SignUpView(CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'accounts/signup.html'

self_practices/practice_1/most_basic_app/rooms/views.py
from django.shortcuts import render

# Create your views here.
from django.views import View
from django.views.generic import ListView
from django.apps import apps

from .models import Salon, Mutfak, KucukOda, YatakOda, Tuvalet


class ListRoomsView(View):
    def get(self, request):
        model_names = []
        room_models = apps.get_app_config('rooms').get_models()
        for model in room_models:
            model_names.append(model.__name__)

        context = {
            "rooms": model_names,
        }
        return render(request, "koridor.html", context)


class SalonView(ListView):
    model = Salon
    template_name = 'rooms/salon.html'
    context_object_name = "items"


class MutfakView(ListView):
    model = Mutfak
    template_name = 'rooms/mutfak.html'
    context_object_name = "items"


class KucukOdaView(ListView):
    model = KucukOda
    template_name = 'rooms/kucukoda.html'
    context_object_name = "items"


class YatakOdaView(ListView):
    model = YatakOda
    template_name = 'rooms/yatakoda.html'
    context_object_name = "items"


class TuvaletView(ListView):
    model = Tuvalet
    template_name = 'rooms/tuvalet.html'
    context_object_name = "items"

self_practices/practice_1/most_basic_app/rooms/templates/rooms/kucukoda.html
{% extends 'base.html' %}

{% block title %}Küçük Oda{% endblock %}

{% block content %}

{% if user.is_authenticated %}
  {{ user.username }}, şu an küçük odasındasın!
  {% for item in items %}
    <p>{{ item.type }} - {{ item.name }}</p>
  {% endfor %}
  <p><a href="{% url 'rooms:koridor' %}">koridora dön</a></p>
  <p><a href="{% url 'logout' %}">evden çık</a></p>
{% else %}
  <p>Giriş yapmamışsın. Kapıdasın</p>

  <a href="{% url 'login' %}">Log In</a>
  <br>
  <a href="{% url 'signup' %}">Sign Up</a>
{% endif %}

{% endblock %}

self_practices/practice_1/most_basic_app/rooms/templates/rooms/mutfak.html
{% extends 'base.html' %}

{% block title %}Salon{% endblock %}

{% block content %}

{% if user.is_authenticated %}
  {{ user.username }}, şu an mutfaktasın!
  {% for item in items %}
    <p>{{ item.type }} - {{ item.name }}</p>
  {% endfor %}
  <p><a href="{% url 'rooms:koridor' %}">koridora dön</a></p>
  <p><a href="{% url 'logout' %}">evden çık</a></p>
{% else %}
  <p>Giriş yapmamışsın. Kapıdasın</p>

  <a href="{% url 'login' %}">Log In</a>
  <br>
  <a href="{% url 'signup' %}">Sign Up</a>
{% endif %}

{% endblock %}

self_practices/practice_1/most_basic_app/rooms/templates/rooms/salon.html
{% extends 'base.html' %}

{% block title %}Salon{% endblock %}

{% block content %}

{% if user.is_authenticated %}
  {{ user.username }}, şu an salondasın!
  {% for item in items %}
    <p>{{ item.type }} - {{ item.name }}</p>
  {% endfor %}
  <p><a href="{% url 'rooms:koridor' %}">koridora dön</a></p>
  <p><a href="{% url 'logout' %}">evden çık</a></p>
{% else %}
  <p>Giriş yapmamışsın. Kapıdasın</p>

  <a href="{% url 'login' %}">Log In</a>
  <br>
  <a href="{% url 'signup' %}">Sign Up</a>
{% endif %}

{% endblock %}

self_practices/practice_1/most_basic_app/rooms/templates/rooms/tuvalet.html
{% extends 'base.html' %}

{% block title %}Salon{% endblock %}

{% block content %}

{% if user.is_authenticated %}
  {{ user.username }}, şu an tuvalettesin!
  {% for item in items %}
    <p>{{ item.type }} - {{ item.name }}</p>
  {% endfor %}
  <p><a href="{% url 'rooms:koridor' %}">koridora dön</a></p>
  <p><a href="{% url 'logout' %}">evden çık</a></p>
{% else %}
  <p>Giriş yapmamışsın. Kapıdasın</p>

  <a href="{% url 'login' %}">Log In</a>
  <br>
  <a href="{% url 'signup' %}">Sign Up</a>
{% endif %}

{% endblock %}

self_practices/practice_1/most_basic_app/rooms/templates/rooms/yatakoda.html
{% extends 'base.html' %}

{% block title %}Salon{% endblock %}

{% block content %}

{% if user.is_authenticated %}
  {{ user.username }}, şu an yatak odasındasın!
  {% for item in items %}
    <p>{{ item.type }} - {{ item.name }}</p>
  {% endfor %}
  <p><a href="{% url 'rooms:koridor' %}">koridora dön</a></p>
  <p><a href="{% url 'logout' %}">evden çık</a></p>
{% else %}
  <p>Giriş yapmamışsın. Kapıdasın</p>

  <a href="{% url 'login' %}">Log In</a>
  <br>
  <a href="{% url 'signup' %}">Sign Up</a>
{% endif %}

{% endblock %}

self_practices/practice_1/most_basic_app/templates/base.html
<html>
<head>
  <meta charset="utf-8">
  <title>{% block title %}Django Practice 1{% endblock %}</title>
</head>
<body>
  <main>
    {% block content %}
    {% endblock %}
  </main>
</body>
</html>

self_practices/practice_1/most_basic_app/templates/home.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
{% if user.is_authenticated %}
  Hi {{ user.username }}!
  <p><a href="{% url 'logout' %}">Log Out</a></p>
{% else %}
  <p>You are not logged in</p>
  <a href="{% url 'login' %}">Log In</a>
  <br>
  <a href="{% url 'signup' %}">Sign Up</a>
{% endif %}
{% endblock %}

self_practices/practice_1/most_basic_app/templates/kapı.html
{% extends 'base.html' %}

{% block title %}Kapı{% endblock %}

{% block content %}
{% if user.is_authenticated %}
  Hi {{ user.username }}!
  <p><a href="{% url 'logout' %}">Log Out</a></p>
{% else %}
  <p>You are not logged in</p>
  <a href="{% url 'login' %}">Log In</a>
  <br>
  <a href="{% url 'signup' %}">Sign Up</a>
{% endif %}
{% endblock %}

self_practices/practice_1/most_basic_app/templates/koridor.html
{% extends 'base.html' %}

{% block title %}Koridor{% endblock %}

{% block content %}

{% if user.is_authenticated %}
  {{ user.username }}, <br> Şu an koridordasın. <br> Hangi odaya girmek istersin?
  <p><a href="{% url 'rooms:salon' %}">Salon</a></p>
  <p><a href="{% url 'rooms:mutfak' %}">Mutfak</a></p>
  <p><a href="{% url 'rooms:yatakoda' %}">YatakOda</a></p>
  <p><a href="{% url 'rooms:kucukoda' %}">KucukOda</a></p>
  <p><a href="{% url 'rooms:tuvalet' %}">Tuvalet</a></p>
  <br>
  <p><a href="{% url 'logout' %}">Log Out</a></p>
{% else %}
  <p>Giriş yapmamışsın. Kapıdasın</p>
  <a href="{% url 'login' %}">Giriş yap</a>
  <br>
  <a href="{% url 'signup' %}">Kayıt ol</a>
{% endif %}

{% endblock %}